name: Ted
favicon: null
layout_spectrum: 0.3438
typography_spectrum: 0.63069
title: Ted Regklis
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c5c5c5'
    - '#ffffff'
    - '#393939'
    - '#979797'
    - '#5a5a5a'
  brandStrength: 1
  lightness: 0.3506354074925184
  saturation: 0.42807539948262274
  rhythmicContrast: 0.5539232795126736
purpose: []
